/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zgusreaqvynyzszllkac"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndXNyZWFxdnlueXpzemxsa2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5MDgyMDUsImV4cCI6MjA5MjQ4NDIwNX0.02G_fL74YYS-VcNC5CeEanWR2X9uSkEfHKudGBU-Am0"