// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-schemes/NavyOrange.tsx": () => import("../components/mockups/color-schemes/NavyOrange.tsx"),
  "./components/mockups/color-schemes/TealCoral.tsx": () => import("../components/mockups/color-schemes/TealCoral.tsx"),
  "./components/mockups/color-schemes/VioletAmber.tsx": () => import("../components/mockups/color-schemes/VioletAmber.tsx")
};
